# Generated by Django 6.0.1 on 2026-02-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='voice_audio',
            field=models.FileField(blank=True, null=True, upload_to='blog_voices/'),
        ),
    ]
